import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NavBar } from "./components/nav-bar.component";
import { Footer } from "./components/footer.component";

// FunnelSans
const funnelSans = localFont({
  src: "./fonts/FunnelSans.ttf",
  display: "swap",
  variable: "--font-funnelsans",
});

const jetBrainsMono = localFont({
  src: "./fonts/JetBrainsMono.ttf",
  display: "swap",
  variable: "--font-jetbrains-mono",
});

export const metadata: Metadata = {
  title: "Rohit Prat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${funnelSans.variable} ${jetBrainsMono.variable} antialiased font-sans page-bg min-h-screen h-full  flex flex-col items-center justify-between w-full`}
      >
        <NavBar />
        <div className="h-full flex-grow w-full">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
