import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";


// FunnelSans
const funnelSans = localFont( {
  src: './fonts/FunnelSans.ttf',
  display: 'swap',
  variable: '--font-funnelsans',

} );

const jetBrainsMono = localFont( {
  src: './fonts/JetBrainsMono.ttf',
  display: 'swap',
  variable: '--font-jetbrains-mono',
} );

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout ( {
  children,
}: Readonly<{
  children: React.ReactNode;
}> )
{
  return (
    <html lang="en">
      <body
        className={ `${ funnelSans.variable } ${ jetBrainsMono.variable } antialiased font-sans` }
      >
        { children }
      </body>
    </html>
  );
}
